### ISSUE TITLE
Bug: improper documentation in the extension readme

### ISSUE THREAD

**Issue by dev-phantom** [yhoungdev/linkbolt#24]
### Describe the bug

In the documentation for the extension, there is no way to run the extension locally 
![Screenshot (7)](https://github.com/yhoungdev/linkbolt/assets/72051159/a2f5ca19-2bde-4f89-922a-1707f0b9539d)

### Steps to reproduce

go to https://github.com/yhoungdev/linkbolt/tree/main/extension
see error

**Comment by yhoungdev** [comment]
Thanks alot sir. i just fixed that
![Screenshot from 2023-07-30 18-32-09](https://github.com/yhoungdev/linkbolt/assets/54102389/bba563f9-9618-4169-8f8a-507b2744063d)
